# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

llikWeibull <- function(Y, eXB, delta, C, rho) {
    .Call('_SpatialCure_llikWeibull', PACKAGE = 'SpatialCure', Y, eXB, delta, C, rho)
}

